#!/usr/bin/env python3
import os
import sys
import requests
import json
import time
import configparser

mess = ""
config = configparser.ConfigParser()
config.read(sys.argv[1])
url = config['BOT']['url']



for x in sys.argv:
    if x != sys.argv[0] and x != sys.argv[1] and sys.argv[2]:
        mess = f"{mess} {x}"
url = f'{url}/api/messages'
print (url)
payload = {"text" : mess ,"ch" : sys.argv[2]}
r = requests.post(url=url, data=payload)
print(r.text)

